-- =========================================================
-- SCRIPT COMPLETO PARA ROCA_MAYA - UNA SOLA EJECUCIÓN
-- Incluye: Tablas, Procedimientos, Triggers, Vistas, Datos
-- =========================================================

CREATE DATABASE IF NOT EXISTS `roca_maya`
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE `roca_maya`;

-- ============================================================
-- 1. CONFIGURACIÓN TEMPORAL (DESACTIVAR SAFE MODE)
-- ============================================================

SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT;
SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS;
SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION;
SET @OLD_TIME_ZONE=@@TIME_ZONE;
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS;
SET @OLD_SQL_MODE=@@SQL_MODE;
SET @OLD_SQL_NOTES=@@SQL_NOTES;

SET NAMES utf8mb4;
SET TIME_ZONE='+00:00';
SET UNIQUE_CHECKS=0;
SET FOREIGN_KEY_CHECKS=0;
SET SQL_MODE='NO_AUTO_VALUE_ON_ZERO';
SET SQL_NOTES=0;
SET SQL_SAFE_UPDATES = 0;

-- ============================================================
-- 2. LIMPIEZA DE OBJETOS EXISTENTES
-- ============================================================

-- Vistas
DROP VIEW IF EXISTS `vw_bitacora_completa`;
DROP VIEW IF EXISTS `vw_citas_completas`;
DROP VIEW IF EXISTS `vw_estadisticas_bitacora`;
DROP VIEW IF EXISTS `vw_estado_seguridad_2fa`;
DROP VIEW IF EXISTS `vw_usuarios_completos`;
DROP VIEW IF EXISTS `vw_citas_recordatorio`;

-- Procedimientos
DROP PROCEDURE IF EXISTS `SP_REGISTRAR_BITACORA`;
DROP PROCEDURE IF EXISTS `SP_ACTIVAR_2FA`;
DROP PROCEDURE IF EXISTS `SP_CONSULTAR_BITACORA`;
DROP PROCEDURE IF EXISTS `SP_DESACTIVAR_2FA`;
DROP PROCEDURE IF EXISTS `SP_VALIDAR_CODIGO_2FA`;
DROP PROCEDURE IF EXISTS `SP_VALIDAR_LOGIN`;

-- Triggers
DROP TRIGGER IF EXISTS `TR_AUDITORIA_CITAS_INSERT`;
DROP TRIGGER IF EXISTS `TR_AUDITORIA_CITAS_UPDATE`;
DROP TRIGGER IF EXISTS `TR_AUDITORIA_CONSULTAS_INSERT`;
DROP TRIGGER IF EXISTS `TR_AUDITORIA_MEDICAMENTOS_INSERT`;
DROP TRIGGER IF EXISTS `TR_AUDITORIA_MEDICAMENTOS_UPDATE`;
DROP TRIGGER IF EXISTS `TR_AUDITORIA_PARAMETROS_UPDATE`;
DROP TRIGGER IF EXISTS `TR_AUDITORIA_ROLES_INSERT`;
DROP TRIGGER IF EXISTS `TR_AUDITORIA_USUARIOS_INSERT`;
DROP TRIGGER IF EXISTS `TR_AUDITORIA_2FA_UPDATE`;
DROP TRIGGER IF EXISTS `TR_AUDITORIA_USUARIOS_UPDATE`;
DROP TRIGGER IF EXISTS `TR_AUDITORIA_PACIENTES_INSERT`;
DROP TRIGGER IF EXISTS `TR_AUDITORIA_PACIENTES_UPDATE`;
DROP TRIGGER IF EXISTS `TR_AUDITORIA_PRESCRIPCIONES_INSERT`;

-- Tablas en orden inverso de dependencias
DROP TABLE IF EXISTS `tbl_prescripcion`;
DROP TABLE IF EXISTS `tbl_preclinica`;
DROP TABLE IF EXISTS `tbl_permisos`;
DROP TABLE IF EXISTS `tbl_ms_hist_contraseña`;
DROP TABLE IF EXISTS `tbl_inventario_medicamentos`;
DROP TABLE IF EXISTS `tbl_historial_medico`;
DROP TABLE IF EXISTS `tbl_doctor_especialidad`;
DROP TABLE IF EXISTS `tbl_consulta_medica`;
DROP TABLE IF EXISTS `tbl_citas`;
DROP TABLE IF EXISTS `tbl_ms_bitacora`;
DROP TABLE IF EXISTS `tbl_paciente`;
DROP TABLE IF EXISTS `tbl_ms_usuario`;
DROP TABLE IF EXISTS `tbl_servicios_medicos`;
DROP TABLE IF EXISTS `tbl_especialidades`;
DROP TABLE IF EXISTS `tbl_ms_parametros`;
DROP TABLE IF EXISTS `tbl_objetos`;
DROP TABLE IF EXISTS `tbl_ms_roles`;

-- ============================================================
-- 3. CREACIÓN DE TABLAS
-- ============================================================

-- ------------------------------------------------------------
-- Tabla: `tbl_ms_roles`
-- ------------------------------------------------------------
CREATE TABLE `tbl_ms_roles` (
  `ID_ROL` int NOT NULL AUTO_INCREMENT,
  `ROL` varchar(50) NOT NULL,
  `DESCRIPCION` varchar(255) DEFAULT NULL,
  `ESTADO` varchar(20) DEFAULT 'ACTIVO',
  `FECHA_CREACION` datetime DEFAULT CURRENT_TIMESTAMP,
  `USUARIO_CREACION` varchar(50) DEFAULT NULL,
  `FECHA_MODIFICACION` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `USUARIO_MODIFICACION` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID_ROL`),
  UNIQUE KEY `ROL` (`ROL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `tbl_ms_roles` (`ID_ROL`, `ROL`, `DESCRIPCION`, `ESTADO`) VALUES
(1, 'ADMINISTRADOR', 'USUARIO CON ACCESO COMPLETO AL SISTEMA', 'ACTIVO'),
(2, 'DOCTOR', 'MÉDICO CON PERMISOS PARA CONSULTAS Y RECETAS', 'ACTIVO'),
(3, 'ENFERMERA', 'PERSONAL DE ENFERMERÍA PARA PRECLÍNICA', 'ACTIVO'),
(4, 'RECEPCIONISTA', 'PERSONAL DE RECEPCIÓN Y CITAS', 'ACTIVO'),
(5, 'PACIENTE', 'USUARIO PACIENTE DEL SISTEMA', 'ACTIVO');

-- ------------------------------------------------------------
-- Tabla: `tbl_objetos`
-- ------------------------------------------------------------
CREATE TABLE `tbl_objetos` (
  `ID_OBJETO` int NOT NULL AUTO_INCREMENT,
  `OBJETO` varchar(100) NOT NULL,
  `DESCRIPCION` varchar(255) DEFAULT NULL,
  `TIPO_OBJETO` varchar(50) DEFAULT NULL,
  `FECHA_CREACION` datetime DEFAULT CURRENT_TIMESTAMP,
  `USUARIO_CREACION` varchar(50) DEFAULT NULL,
  `FECHA_MODIFICACION` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `USUARIO_MODIFICACION` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID_OBJETO`),
  UNIQUE KEY `OBJETO` (`OBJETO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `tbl_objetos` (`OBJETO`, `DESCRIPCION`, `TIPO_OBJETO`, `USUARIO_CREACION`) VALUES
('Citas médicas', 'Gestión de citas médicas', 'Servicio', 'SISTEMA'),
('Consultas Médicas', 'Gestión de consultas médicas', 'Servicio', 'SISTEMA'),
('Preclínica', 'Gestión de preclínica', 'Servicio', 'SISTEMA'),
('Especialidades Médicas', 'Gestión de especialidades', 'Servicio', 'SISTEMA'),
('Pacientes', 'Gestión de pacientes', 'Administración', 'SISTEMA'),
('Historial médico', 'Gestión de historial médico', 'Administración', 'SISTEMA'),
('Bitácora', 'Gestión de bitácora', 'Seguridad', 'SISTEMA'),
('Usuarios', 'Gestión de usuarios', 'Seguridad', 'SISTEMA'),
('Respaldo de Base de Datos', 'Descargar respaldo de la base de datos', 'Seguridad', 'SISTEMA'),
('Restaurar Base de Datos', 'Restaurar base de datos desde archivo .sql', 'Seguridad', 'SISTEMA'),
('Parámetros de Seguridad', 'Configuración de parámetros de seguridad', 'Seguridad', 'SISTEMA'),
('Farmacia / Inventario', 'Gestión de inventario de medicamentos', 'Farmacia', 'SISTEMA');

-- ------------------------------------------------------------
-- Tabla: `tbl_permisos`
-- ------------------------------------------------------------
CREATE TABLE `tbl_permisos` (
  `ID_PERMISO` int NOT NULL AUTO_INCREMENT,
  `ID_ROL` int NOT NULL,
  `ID_OBJETO` int NOT NULL,
  `PERMISO_INSERCION` tinyint(1) DEFAULT '0',
  `PERMISO_ELIMINACION` tinyint(1) DEFAULT '0',
  `PERMISO_ACTUALIZACION` tinyint(1) DEFAULT '0',
  `PERMISO_CONSULTA` tinyint(1) DEFAULT '0',
  `FECHA_CREACION` datetime DEFAULT CURRENT_TIMESTAMP,
  `USUARIO_CREACION` varchar(50) DEFAULT NULL,
  `FECHA_MODIFICACION` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `USUARIO_MODIFICACION` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID_PERMISO`),
  UNIQUE KEY `unique_rol_objeto` (`ID_ROL`,`ID_OBJETO`),
  KEY `ID_OBJETO` (`ID_OBJETO`),
  CONSTRAINT `tbl_permisos_ibfk_1` FOREIGN KEY (`ID_ROL`) REFERENCES `tbl_ms_roles` (`ID_ROL`),
  CONSTRAINT `tbl_permisos_ibfk_2` FOREIGN KEY (`ID_OBJETO`) REFERENCES `tbl_objetos` (`ID_OBJETO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Permisos para ADMINISTRADOR
INSERT INTO `tbl_permisos` (`ID_ROL`, `ID_OBJETO`, `PERMISO_CONSULTA`, `PERMISO_INSERCION`, `PERMISO_ACTUALIZACION`, `PERMISO_ELIMINACION`, `USUARIO_CREACION`)
SELECT 1, ID_OBJETO, 1, 1, 1, 1, 'SISTEMA'
FROM tbl_objetos;

-- Permisos para DOCTOR
INSERT INTO `tbl_permisos` (`ID_ROL`, `ID_OBJETO`, `PERMISO_CONSULTA`, `PERMISO_INSERCION`, `PERMISO_ACTUALIZACION`, `PERMISO_ELIMINACION`, `USUARIO_CREACION`)
SELECT 2, ID_OBJETO, 1, 1, 1, 0, 'SISTEMA'
FROM tbl_objetos
WHERE ID_OBJETO IN (2, 6);

-- Permisos para ENFERMERA
INSERT INTO `tbl_permisos` (`ID_ROL`, `ID_OBJETO`, `PERMISO_CONSULTA`, `PERMISO_INSERCION`, `PERMISO_ACTUALIZACION`, `PERMISO_ELIMINACION`, `USUARIO_CREACION`)
SELECT 3, ID_OBJETO, 1, 1, 1, 0, 'SISTEMA'
FROM tbl_objetos
WHERE ID_OBJETO IN (3, 5);

-- Permisos para RECEPCIONISTA
INSERT INTO `tbl_permisos` (`ID_ROL`, `ID_OBJETO`, `PERMISO_CONSULTA`, `PERMISO_INSERCION`, `PERMISO_ACTUALIZACION`, `PERMISO_ELIMINACION`, `USUARIO_CREACION`)
SELECT 4, ID_OBJETO, 1, 1, 1, 0, 'SISTEMA'
FROM tbl_objetos
WHERE ID_OBJETO IN (1, 5);

-- ------------------------------------------------------------
-- Tabla: `tbl_ms_parametros`
-- ------------------------------------------------------------
CREATE TABLE `tbl_ms_parametros` (
  `ID_PARAMETRO` int NOT NULL AUTO_INCREMENT,
  `PARAMETRO` varchar(100) NOT NULL,
  `VALOR` varchar(255) NOT NULL,
  `DESCRIPCION` varchar(500) DEFAULT NULL,
  `FECHA_CREACION` datetime DEFAULT CURRENT_TIMESTAMP,
  `USUARIO_CREACION` varchar(50) DEFAULT NULL,
  `FECHA_MODIFICACION` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `USUARIO_MODIFICACION` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID_PARAMETRO`),
  UNIQUE KEY `PARAMETRO` (`PARAMETRO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `tbl_ms_parametros` (`ID_PARAMETRO`, `PARAMETRO`, `VALOR`, `DESCRIPCION`) VALUES
(1, 'ADMIN_INTENTOS_INVALIDOS', '3', 'NÚMERO MÁXIMO DE INTENTOS DE LOGIN FALLIDOS PERMITIDOS'),
(2, 'ADMIN_PREGUNTAS', '3', 'NÚMERO DE PREGUNTAS DE SEGURIDAD REQUERIDAS'),
(3, 'ADMIN_CORREO', 'correo@dominio.com', 'CORREO ELECTRÓNICO PARA ENVÍO DE NOTIFICACIONES'),
(4, 'ADMIN_CPUERTO', '9999', 'PUERTO PARA CONFIGURACIÓN DEL SERVIDOR'),
(5, 'ADMIN_CUSER', 'USUARIO', 'USUARIO PARA CONFIGURACIÓN DEL SERVIDOR'),
(6, 'ADMIN_CPASS', 'PASSWORD', 'CONTRASEÑA PARA CONFIGURACIÓN DEL SERVIDOR'),
(7, 'ADMIN_VIGENCIA', '30', 'DÍAS DE VIGENCIA DE LA CONTRASEÑA'),
(8, 'ADMIN_DIAS_VIGENCIA', '360', 'DÍAS DE VIGENCIA DE LA CUENTA DE USUARIO'),
(9, 'IMPUESTO', '15', 'PORCENTAJE DE IMPUESTO APLICABLE'),
(10, 'SYS_NOMBRE', 'SISTEMA ROCA MAYA', 'NOMBRE DEL SISTEMA'),
(11, 'MIN_CONTRASEÑA', '8', 'LONGITUD MÍNIMA DE LA CONTRASEÑA'),
(12, 'MAX_CONTRASEÑA', '15', 'LONGITUD MÁXIMA DE LA CONTRASEÑA'),
(13, 'BITACORA_RETENCION_DIAS', '365', 'DÍAS DE RETENCIÓN DE REGISTROS EN BITÁCORA'),
(14, 'BITACORA_LOG_ERRORS', 'SI', 'REGISTRAR ERRORES EN BITÁCORA (SI/NO)'),
(15, 'BITACORA_LOG_LOGINS', 'SI', 'REGISTRAR INICIOS DE SESIÓN EN BITÁCORA'),
(16, '2FA_MAX_INTENTOS', '3', 'MÁXIMO DE INTENTOS FALLIDOS DE CÓDIGO 2FA'),
(17, '2FA_TIEMPO_BLOQUEO_MIN', '30', 'MINUTOS DE BLOQUEO POR INTENTOS FALLIDOS 2FA'),
(18, '2FA_OBLIGATORIO_ADMIN', 'SI', '2FA OBLIGATORIO PARA USUARIOS ADMINISTRADORES');

-- ------------------------------------------------------------
-- Tabla: `tbl_especialidades`
-- ------------------------------------------------------------
CREATE TABLE `tbl_especialidades` (
  `ID_ESPECIALIDAD` int NOT NULL AUTO_INCREMENT,
  `NOMBRE_ESPECIALIDAD` varchar(100) NOT NULL,
  `DESCRIPCION` text,
  `COLOR_HEXADECIMAL` varchar(7) DEFAULT '#3498DB',
  `ICONO` varchar(50) DEFAULT NULL,
  `ESTADO` enum('ACTIVA','INACTIVA') DEFAULT 'ACTIVA',
  `FECHA_CREACION` datetime DEFAULT CURRENT_TIMESTAMP,
  `USUARIO_CREACION` varchar(50) DEFAULT NULL,
  `USUARIO_MODIFICACION` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID_ESPECIALIDAD`),
  UNIQUE KEY `NOMBRE_ESPECIALIDAD` (`NOMBRE_ESPECIALIDAD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `tbl_especialidades` (`ID_ESPECIALIDAD`, `NOMBRE_ESPECIALIDAD`, `DESCRIPCION`, `COLOR_HEXADECIMAL`, `ESTADO`) VALUES
(1, 'MEDICINA GENERAL', 'ATENCIÓN PRIMARIA Y GENERAL', '#3498DB', 'ACTIVA'),
(2, 'PEDIATRÍA', 'ESPECIALIDAD EN NIÑOS', '#3498DB', 'ACTIVA'),
(3, 'GINECOLOGÍA', 'SALUD FEMENINA', '#3498DB', 'ACTIVA'),
(4, 'CARDIOLOGÍA', 'ESPECIALIDAD DEL CORAZÓN', '#3498db', 'ACTIVA'),
(5, 'DERMATOLOGÍA', 'ESPECIALIDAD DE LA PIEL', '#3498DB', 'ACTIVA');

-- ------------------------------------------------------------
-- Tabla: `tbl_servicios_medicos`
-- ------------------------------------------------------------
CREATE TABLE `tbl_servicios_medicos` (
  `ID_SERVICIO` int NOT NULL AUTO_INCREMENT,
  `NOMBRE_SERVICIO` varchar(200) NOT NULL,
  `DESCRIPCION` text,
  `PRECIO_UNITARIO` decimal(10,2) NOT NULL,
  `CODIGO_CIEO_10` varchar(20) DEFAULT NULL,
  `CODIGO_CUPS` varchar(20) DEFAULT NULL,
  `TIPO_SERVICIO` enum('CONSULTA','EXAMEN','PROCEDIMIENTO','TERAPIA','HOSPITALIZACION') DEFAULT 'CONSULTA',
  `CATEGORIA` varchar(100) DEFAULT NULL,
  `ESTADO` enum('ACTIVO','INACTIVO') DEFAULT 'ACTIVO',
  `FECHA_CREACION` datetime DEFAULT CURRENT_TIMESTAMP,
  `USUARIO_CREACION` varchar(50) DEFAULT NULL,
  `USUARIO_MODIFICACION` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID_SERVICIO`),
  KEY `idx_servicio_tipo` (`TIPO_SERVICIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `tbl_servicios_medicos` (`ID_SERVICIO`, `NOMBRE_SERVICIO`, `DESCRIPCION`, `PRECIO_UNITARIO`, `TIPO_SERVICIO`, `ESTADO`) VALUES
(1, 'CONSULTA GENERAL', 'CONSULTA MÉDICA GENERAL', 500.00, 'CONSULTA', 'ACTIVO'),
(2, 'CONSULTA ESPECIALIDAD', 'CONSULTA CON ESPECIALISTA', 800.00, 'CONSULTA', 'ACTIVO'),
(3, 'EXAMEN DE SANGRE', 'HEMOGRAMA COMPLETO', 300.00, 'EXAMEN', 'ACTIVO'),
(4, 'RAYOS X', 'RADIOGRAFÍA SIMPLE', 450.00, 'EXAMEN', 'ACTIVO'),
(5, 'ELECTROCARDIOGRAMA', 'ECG ESTÁNDAR', 600.00, 'EXAMEN', 'ACTIVO');

-- ------------------------------------------------------------
-- Tabla: `tbl_ms_usuario`
-- ------------------------------------------------------------
CREATE TABLE `tbl_ms_usuario` (
  `ID_USUARIO` int NOT NULL AUTO_INCREMENT,
  `USUARIO` varchar(50) NOT NULL,
  `NOMBRE_USUARIO` varchar(100) NOT NULL,
  `ESTADO` varchar(20) NOT NULL DEFAULT 'NUEVO',
  `CONTRASENA` varchar(255) NOT NULL,
  `ID_ROL` int NOT NULL,
  `FECHA_ULTIMA_CONEXION` datetime DEFAULT NULL,
  `FECHA_VENCIMIENTO` date DEFAULT NULL,
  `CORREO_ELECTRONICO` varchar(100) DEFAULT NULL,
  `INTENTOS_FALLIDOS` int DEFAULT '0',
  `GOOGLE_ID` varchar(100) DEFAULT NULL,
  `TWO_FACTOR_ENABLED` tinyint(1) DEFAULT '0',
  `TWO_FACTOR_SECRET` varchar(100) DEFAULT NULL,
  `SECRET_2FA` varchar(255) DEFAULT NULL,
  `ACTIVO_2FA` tinyint(1) NOT NULL DEFAULT '0',
  `FECHA_ACTIVACION_2FA` datetime DEFAULT NULL,
  `ULTIMO_CODIGO_2FA` varchar(10) DEFAULT NULL,
  `INTENTOS_2FA_FALLIDOS` int DEFAULT '0',
  `BLOQUEO_2FA_HASTA` datetime DEFAULT NULL,
  `FECHA_CREACION` datetime DEFAULT CURRENT_TIMESTAMP,
  `USUARIO_CREACION` varchar(50) DEFAULT NULL,
  `FECHA_MODIFICACION` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `USUARIO_MODIFICACION` varchar(50) DEFAULT NULL,
  `CODIGO_RECUPERACION` int DEFAULT NULL,
  `EXPIRA_CODIGO` datetime DEFAULT NULL,
  PRIMARY KEY (`ID_USUARIO`),
  UNIQUE KEY `USUARIO` (`USUARIO`),
  UNIQUE KEY `GOOGLE_ID` (`GOOGLE_ID`),
  KEY `ID_ROL` (`ID_ROL`),
  KEY `idx_usuario_estado` (`ESTADO`),
  KEY `idx_usuario_fecha_vencimiento` (`FECHA_VENCIMIENTO`),
  KEY `idx_usuario_2fa` (`ACTIVO_2FA`),
  CONSTRAINT `tbl_ms_usuario_ibfk_1` FOREIGN KEY (`ID_ROL`) REFERENCES `tbl_ms_roles` (`ID_ROL`),
  CONSTRAINT `tbl_ms_usuario_chk_1` CHECK ((`ESTADO` in (_utf8mb4'ACTIVO',_utf8mb4'INACTIVO',_utf8mb4'BLOQUEADO',_utf8mb4'NUEVO')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `tbl_ms_usuario` (`ID_USUARIO`, `USUARIO`, `NOMBRE_USUARIO`, `ESTADO`, `CONTRASENA`, `ID_ROL`, `ACTIVO_2FA`, `CORREO_ELECTRONICO`) VALUES
(1, 'ADMIN', 'ADMINISTRADOR DEL SISTEMA', 'ACTIVO', '$2b$10$KOIds/jUOwiHUMv0gVqFC.bRHcozW7ON1sbVNo0ldDNUFCfAdNyqq', 1, 1, 'admin@rocamaya.com'),
(2, 'DR.Denis', 'DENIS SANDOVAL', 'ACTIVO', '$2b$10$Temp123!', 2, 0, 'dr.garcia@rocamaya.com'),
(3, 'ENF.ROSA', 'LIC. ROSA MARÍA HERNÁNDEZ', 'ACTIVO', '$2b$10$Temp123!', 3, 0, 'enf.rosa@rocamaya.com'),
(4, 'RECEP.ANA', 'ANA LUCÍA GÓMEZ', 'ACTIVO', '$2b$10$Temp123!', 4, 0, 'recepcion@rocamaya.com');

-- ------------------------------------------------------------
-- Tabla: `tbl_paciente`
-- ------------------------------------------------------------
CREATE TABLE `tbl_paciente` (
  `ID_PACIENTE` int NOT NULL AUTO_INCREMENT,
  `NOMBRES` varchar(100) NOT NULL,
  `APELLIDOS` varchar(100) NOT NULL,
  `FECHA_NACIMIENTO` date DEFAULT NULL,
  `GENERO` enum('MASCULINO','FEMENINO','OTRO','PREFIERO_NO_DECIR') DEFAULT NULL,
  `DIRECCION` varchar(255) DEFAULT NULL,
  `TELEFONO` varchar(20) DEFAULT NULL,
  `CORREO_ELECTRONICO` varchar(100) DEFAULT NULL,
  `TIPO_DOCUMENTO_IDENTIDAD` enum('DNI','PASAPORTE','LICENCIA','OTRO') DEFAULT 'DNI',
  `NUMERO_DOCUMENTO_IDENTIDAD` varchar(50) DEFAULT NULL,
  `RTN_PACIENTE` varchar(50) DEFAULT NULL,
  `ESTADO_CIVIL` enum('SOLTERO','CASADO','DIVORCIADO','VIUDO','UNION_LIBRE') DEFAULT NULL,
  `OCUPACION` varchar(100) DEFAULT NULL,
  `NOMBRE_CONTACTO_EMERGENCIA` varchar(200) DEFAULT NULL,
  `TELEFONO_CONTACTO_EMERGENCIA` varchar(20) DEFAULT NULL,
  `PARENTESCO_CONTACTO_EMERGENCIA` varchar(50) DEFAULT NULL,
  `ESTADO` enum('ACTIVO','INACTIVO','BLOQUEADO') DEFAULT 'ACTIVO',
  `FECHA_REGISTRO` datetime DEFAULT CURRENT_TIMESTAMP,
  `ID_USUARIO_REGISTRO` int DEFAULT NULL,
  `FECHA_ACTUALIZACION` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `USUARIO_CREACION` varchar(50) DEFAULT NULL,
  `USUARIO_MODIFICACION` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID_PACIENTE`),
  UNIQUE KEY `NUMERO_DOCUMENTO_IDENTIDAD` (`NUMERO_DOCUMENTO_IDENTIDAD`),
  KEY `ID_USUARIO_REGISTRO` (`ID_USUARIO_REGISTRO`),
  KEY `idx_paciente_documento` (`NUMERO_DOCUMENTO_IDENTIDAD`),
  KEY `idx_paciente_nombres` (`NOMBRES`,`APELLIDOS`),
  KEY `idx_paciente_estado` (`ESTADO`),
  CONSTRAINT `tbl_paciente_ibfk_1` FOREIGN KEY (`ID_USUARIO_REGISTRO`) REFERENCES `tbl_ms_usuario` (`ID_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- Tabla: `tbl_ms_bitacora`
-- ------------------------------------------------------------
CREATE TABLE `tbl_ms_bitacora` (
  `ID_BITACORA` int NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` int DEFAULT NULL,
  `FECHA_HORA` datetime DEFAULT CURRENT_TIMESTAMP,
  `ACCION` varchar(100) NOT NULL,
  `DESCRIPCION` text,
  `MODULO` varchar(50) DEFAULT NULL,
  `ID_REGISTRO_AFECTADO` int DEFAULT NULL,
  `TABLA_AFECTADA` varchar(50) DEFAULT NULL,
  `IP_CLIENTE` varchar(45) DEFAULT NULL,
  `USER_AGENT` varchar(500) DEFAULT NULL,
  `ESTADO_OPERACION` enum('EXITO','ERROR','ADVERTENCIA') DEFAULT 'EXITO',
  `DETALLE_ERROR` text,
  `USUARIO_CREACION` varchar(50) DEFAULT NULL,
  `FECHA_CREACION` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID_BITACORA`),
  KEY `idx_bitacora_usuario` (`ID_USUARIO`),
  KEY `idx_bitacora_fecha` (`FECHA_HORA`),
  KEY `idx_bitacora_modulo` (`MODULO`),
  KEY `idx_bitacora_accion` (`ACCION`),
  CONSTRAINT `tbl_ms_bitacora_ibfk_1` FOREIGN KEY (`ID_USUARIO`) REFERENCES `tbl_ms_usuario` (`ID_USUARIO`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- Tabla: `tbl_citas`
-- ------------------------------------------------------------
CREATE TABLE `tbl_citas` (
  `ID_CITA` int NOT NULL AUTO_INCREMENT,
  `ID_PACIENTE` int NOT NULL,
  `ID_DOCTOR` int NOT NULL,
  `FECHA_CITA` datetime NOT NULL,
  `FECHA_FIN_ESTIMADA` datetime DEFAULT NULL,
  `DURACION_ESTIMADA_MIN` int DEFAULT '30',
  `ESTADO` enum('PROGRAMADA','CONFIRMADA','PRECLINICA','CONSULTA_MEDICA','FINALIZADA','CANCELADA','NO_ASISTIO') DEFAULT 'PROGRAMADA',
  `MOTIVO_CONSULTA` text,
  `ID_USUARIOCREADOR` int NOT NULL,
  `FECHA_CREACION` datetime DEFAULT CURRENT_TIMESTAMP,
  `USUARIO_CREACION` varchar(50) DEFAULT NULL,
  `FECHA_MODIFICACION` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `USUARIO_MODIFICACION` varchar(50) DEFAULT NULL,
  `OBSERVACIONES` text,
  `PRIORIDAD` enum('NORMAL','URGENTE','ALTA') DEFAULT 'NORMAL',
  `TIPO_CITA` enum('PRIMERA_VEZ','CONTROL','EMERGENCIA','PROCEDIMIENTO') DEFAULT 'PRIMERA_VEZ',
  `CANAL_REGISTRO` enum('PRESENCIAL','TELEFONO','WEB','MOVIL','API') DEFAULT 'PRESENCIAL',
  PRIMARY KEY (`ID_CITA`),
  KEY `ID_USUARIOCREADOR` (`ID_USUARIOCREADOR`),
  KEY `idx_citas_paciente` (`ID_PACIENTE`),
  KEY `idx_citas_doctor` (`ID_DOCTOR`),
  KEY `idx_citas_estado` (`ESTADO`),
  KEY `idx_citas_fecha` (`FECHA_CITA`),
  KEY `idx_citas_creacion` (`FECHA_CREACION`),
  KEY `idx_citas_modificacion` (`FECHA_MODIFICACION`),
  CONSTRAINT `tbl_citas_ibfk_1` FOREIGN KEY (`ID_PACIENTE`) REFERENCES `tbl_paciente` (`ID_PACIENTE`),
  CONSTRAINT `tbl_citas_ibfk_2` FOREIGN KEY (`ID_DOCTOR`) REFERENCES `tbl_ms_usuario` (`ID_USUARIO`),
  CONSTRAINT `tbl_citas_ibfk_3` FOREIGN KEY (`ID_USUARIOCREADOR`) REFERENCES `tbl_ms_usuario` (`ID_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- Tabla: `tbl_consulta_medica`
-- ------------------------------------------------------------
CREATE TABLE `tbl_consulta_medica` (
  `ID_CONSULTA` int NOT NULL AUTO_INCREMENT,
  `ID_CITA` int NOT NULL,
  `ID_PACIENTE` int NOT NULL,
  `ID_DOCTOR` int NOT NULL,
  `MOTIVO_CONSULTA` text,
  `SINTOMAS` json DEFAULT NULL,
  `EXAMEN_FISICO` json DEFAULT NULL,
  `DIAGNOSTICO_PRINCIPAL` text,
  `CODIGO_CIE10_PRINCIPAL` varchar(10) DEFAULT NULL,
  `DIAGNOSTICO_SECUNDARIO` text,
  `CODIGO_CIE10_SECUNDARIO` varchar(10) DEFAULT NULL,
  `TRATAMIENTO` text,
  `RECOMENDACIONES` text,
  `OBSERVACIONES` text,
  `FECHA_CONSULTA` datetime DEFAULT CURRENT_TIMESTAMP,
  `PROXIMA_CITA_RECOMENDADA` date DEFAULT NULL,
  `TIPO_CONSULTA` enum('GENERAL','ESPECIALIDAD','CONTROL','EMERGENCIA') DEFAULT 'GENERAL',
  `USUARIO_CREACION` varchar(50) DEFAULT NULL,
  `USUARIO_MODIFICACION` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID_CONSULTA`),
  UNIQUE KEY `ID_CITA` (`ID_CITA`),
  KEY `ID_DOCTOR` (`ID_DOCTOR`),
  KEY `idx_consulta_cita` (`ID_CITA`),
  KEY `idx_consulta_paciente` (`ID_PACIENTE`),
  KEY `idx_consulta_fecha` (`FECHA_CONSULTA`),
  CONSTRAINT `tbl_consulta_medica_ibfk_1` FOREIGN KEY (`ID_CITA`) REFERENCES `tbl_citas` (`ID_CITA`) ON DELETE CASCADE,
  CONSTRAINT `tbl_consulta_medica_ibfk_2` FOREIGN KEY (`ID_PACIENTE`) REFERENCES `tbl_paciente` (`ID_PACIENTE`),
  CONSTRAINT `tbl_consulta_medica_ibfk_3` FOREIGN KEY (`ID_DOCTOR`) REFERENCES `tbl_ms_usuario` (`ID_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- Tabla: `tbl_doctor_especialidad`
-- ------------------------------------------------------------
CREATE TABLE `tbl_doctor_especialidad` (
  `ID_DOCTOR_ESPECIALIDAD` int NOT NULL AUTO_INCREMENT,
  `ID_DOCTOR` int NOT NULL,
  `ID_ESPECIALIDAD` int NOT NULL,
  `FECHA_ASIGNACION` date DEFAULT (curdate()),
  `ESTADO` enum('ACTIVA','INACTIVA') DEFAULT 'ACTIVA',
  `ES_PRIMARIA` tinyint(1) DEFAULT '0',
  `ANIOS_EXPERIENCIA` int DEFAULT '0',
  `FECHA_CREACION` datetime DEFAULT CURRENT_TIMESTAMP,
  `USUARIO_CREACION` varchar(50) DEFAULT NULL,
  `FECHA_MODIFICACION` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `USUARIO_MODIFICACION` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID_DOCTOR_ESPECIALIDAD`),
  UNIQUE KEY `UNIQUE_TBL_DOCTOR_ESPECIALIDAD` (`ID_DOCTOR`,`ID_ESPECIALIDAD`),
  KEY `ID_ESPECIALIDAD` (`ID_ESPECIALIDAD`),
  KEY `idx_doctor_especialidad_estado` (`ESTADO`),
  CONSTRAINT `tbl_doctor_especialidad_ibfk_1` FOREIGN KEY (`ID_DOCTOR`) REFERENCES `tbl_ms_usuario` (`ID_USUARIO`) ON DELETE CASCADE,
  CONSTRAINT `tbl_doctor_especialidad_ibfk_2` FOREIGN KEY (`ID_ESPECIALIDAD`) REFERENCES `tbl_especialidades` (`ID_ESPECIALIDAD`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- Tabla: `tbl_historial_medico`
-- ------------------------------------------------------------
CREATE TABLE `tbl_historial_medico` (
  `ID_HISTORIAL` int NOT NULL AUTO_INCREMENT,
  `ID_PACIENTE` int NOT NULL,
  `ALERGIAS` json DEFAULT NULL,
  `ENFERMEDADES_CRONICAS` json DEFAULT NULL,
  `CIRUGIAS_PREVIAS` json DEFAULT NULL,
  `MEDICAMENTOS_ACTUALES` json DEFAULT NULL,
  `ANTECEDENTES_FAMILIARES` json DEFAULT NULL,
  `HABITOS` json DEFAULT NULL COMMENT 'TABACO, ALCOHOL, EJERCICIO, ETC.',
  `VACUNAS` json DEFAULT NULL,
  `NOTAS_IMPORTANTES` text,
  `FECHA_ACTUALIZACION` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ID_USUARIO_ACTUALIZO` int DEFAULT NULL,
  `USUARIO_CREACION` varchar(50) DEFAULT NULL,
  `USUARIO_MODIFICACION` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID_HISTORIAL`),
  UNIQUE KEY `ID_PACIENTE` (`ID_PACIENTE`),
  KEY `ID_USUARIO_ACTUALIZO` (`ID_USUARIO_ACTUALIZO`),
  CONSTRAINT `tbl_historial_medico_ibfk_1` FOREIGN KEY (`ID_PACIENTE`) REFERENCES `tbl_paciente` (`ID_PACIENTE`) ON DELETE CASCADE,
  CONSTRAINT `tbl_historial_medico_ibfk_2` FOREIGN KEY (`ID_USUARIO_ACTUALIZO`) REFERENCES `tbl_ms_usuario` (`ID_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- Tabla: `tbl_inventario_medicamentos`
-- ------------------------------------------------------------
CREATE TABLE `tbl_inventario_medicamentos` (
  `ID_MEDICAMENTO` int NOT NULL AUTO_INCREMENT,
  `NOMBRE_MEDICAMENTO` varchar(255) NOT NULL,
  `NOMBRE_GENERICO` varchar(255) DEFAULT NULL,
  `DESCRIPCION` text,
  `PRESENTACION` varchar(100) DEFAULT NULL,
  `CONCENTRACION` varchar(50) DEFAULT NULL,
  `VIA_ADMINISTRACION` varchar(50) DEFAULT NULL,
  `STOCK_ACTUAL` int DEFAULT '0',
  `STOCK_MINIMO` int DEFAULT '10',
  `STOCK_MAXIMO` int DEFAULT '100',
  `PRECIO_COMPRA` decimal(10,2) DEFAULT NULL,
  `PRECIO_VENTA` decimal(10,2) DEFAULT NULL,
  `LOTE` varchar(100) DEFAULT NULL,
  `FECHA_VENCIMIENTO` date DEFAULT NULL,
  `PROVEEDOR` varchar(255) DEFAULT NULL,
  `REQUIERE_RECETA` tinyint(1) DEFAULT '1',
  `ESTADO` enum('ACTIVO','INACTIVO','VENCIDO') DEFAULT 'ACTIVO',
  `FECHA_REGISTRO` datetime DEFAULT CURRENT_TIMESTAMP,
  `ID_USUARIO_REGISTRO` int DEFAULT NULL,
  `USUARIO_CREACION` varchar(50) DEFAULT NULL,
  `USUARIO_MODIFICACION` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID_MEDICAMENTO`),
  KEY `ID_USUARIO_REGISTRO` (`ID_USUARIO_REGISTRO`),
  KEY `idx_medicamento_nombre` (`NOMBRE_MEDICAMENTO`),
  KEY `idx_medicamento_vencimiento` (`FECHA_VENCIMIENTO`),
  KEY `idx_medicamento_stock` (`STOCK_ACTUAL`),
  CONSTRAINT `tbl_inventario_medicamentos_ibfk_1` FOREIGN KEY (`ID_USUARIO_REGISTRO`) REFERENCES `tbl_ms_usuario` (`ID_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `tbl_inventario_medicamentos` (`ID_MEDICAMENTO`, `NOMBRE_MEDICAMENTO`, `NOMBRE_GENERICO`, `DESCRIPCION`, `PRESENTACION`, `CONCENTRACION`, `VIA_ADMINISTRACION`, `STOCK_ACTUAL`, `STOCK_MINIMO`, `STOCK_MAXIMO`, `PRECIO_COMPRA`, `PRECIO_VENTA`, `FECHA_VENCIMIENTO`, `PROVEEDOR`, `ESTADO`) VALUES
(1, 'LOSARTAN', 'LOSARTAN POTÁSICO', 'ANTAGONISTA DE RECEPTORES DE ANGIOTENSINA II', 'TABLETAS', '100MG', 'ORAL', 100, 20, 200, 3.50, 5.50, '2025-12-31', 'LABORATORIOS FARMACÉUTICOS S.A.', 'ACTIVO'),
(2, 'HIDROCLOROTIAZIDA', 'HIDROCLOROTIAZIDA', 'DIURÉTICO TIAZÍDICO', 'TABLETAS', '12.5MG', 'ORAL', 150, 30, 300, 1.80, 3.20, '2025-10-31', 'LABORATORIOS MÉDICOS HONDUREÑOS', 'ACTIVO');

-- ------------------------------------------------------------
-- Tabla: `tbl_ms_hist_contraseña`
-- ------------------------------------------------------------
CREATE TABLE `tbl_ms_hist_contraseña` (
  `ID_HIST` int NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` int NOT NULL,
  `CONTRASENA` varchar(255) NOT NULL,
  `FECHA_CREACION` datetime DEFAULT CURRENT_TIMESTAMP,
  `USUARIO_CREACION` varchar(50) DEFAULT NULL,
  `FECHA_MODIFICACION` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `USUARIO_MODIFICACION` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID_HIST`),
  KEY `idx_hist_usuario` (`ID_USUARIO`),
  CONSTRAINT `tbl_ms_hist_contraseña_ibfk_1` FOREIGN KEY (`ID_USUARIO`) REFERENCES `tbl_ms_usuario` (`ID_USUARIO`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- Tabla: `tbl_preclinica`
-- ------------------------------------------------------------
CREATE TABLE `tbl_preclinica` (
  `ID_PRECLINICA` int NOT NULL AUTO_INCREMENT,
  `ID_CITA` int NOT NULL,
  `ID_USUARIO_ENFERMERIA` int NOT NULL,
  `FECHA_REGISTRO` datetime DEFAULT CURRENT_TIMESTAMP,
  `TEMPERATURA` decimal(4,2) DEFAULT NULL,
  `PRESION_SISTOLICA` int DEFAULT NULL,
  `PRESION_DIASTOLICA` int DEFAULT NULL,
  `FRECUENCIA_CARDIACA` int DEFAULT NULL,
  `FRECUENCIA_RESPIRATORIA` int DEFAULT NULL,
  `SATURACION_OXIGENO` decimal(5,2) DEFAULT NULL,
  `PESO` decimal(5,2) DEFAULT NULL,
  `TALLA` decimal(5,2) DEFAULT NULL,
  `IMC` decimal(4,2) GENERATED ALWAYS AS ((`PESO` / (`TALLA` * `TALLA`))) STORED,
  `GLUCOSA` decimal(5,2) DEFAULT NULL,
  `PERIMETRO_ABDOMINAL` decimal(5,2) DEFAULT NULL,
  `OBSERVACIONES` text,
  `ESTADO_GENERAL` enum('BUENO','REGULAR','MALO') DEFAULT 'BUENO',
  `SIGNOS_VITALES_JSON` json DEFAULT NULL,
  `USUARIO_CREACION` varchar(50) DEFAULT NULL,
  `USUARIO_MODIFICACION` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID_PRECLINICA`),
  UNIQUE KEY `ID_CITA` (`ID_CITA`),
  KEY `ID_USUARIO_ENFERMERIA` (`ID_USUARIO_ENFERMERIA`),
  KEY `idx_preclinica_cita` (`ID_CITA`),
  CONSTRAINT `tbl_preclinica_ibfk_1` FOREIGN KEY (`ID_CITA`) REFERENCES `tbl_citas` (`ID_CITA`) ON DELETE CASCADE,
  CONSTRAINT `tbl_preclinica_ibfk_2` FOREIGN KEY (`ID_USUARIO_ENFERMERIA`) REFERENCES `tbl_ms_usuario` (`ID_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- Tabla: `tbl_prescripcion`
-- ------------------------------------------------------------
CREATE TABLE `tbl_prescripcion` (
  `ID_PRESCRIPCION` int NOT NULL AUTO_INCREMENT,
  `ID_CONSULTA` int NOT NULL,
  `ID_MEDICAMENTO` int NOT NULL,
  `FECHA_PRESCRIPCION` datetime DEFAULT CURRENT_TIMESTAMP,
  `DOSIS` varchar(50) NOT NULL,
  `FRECUENCIA` varchar(50) DEFAULT NULL,
  `DURACION` varchar(50) DEFAULT NULL,
  `CANTIDAD_TOTAL` int DEFAULT NULL,
  `INSTRUCCIONES_ADICIONALES` text,
  `ESTADO` enum('ACTIVA','COMPLETADA','SUSPENDIDA') DEFAULT 'ACTIVA',
  `USUARIO_CREACION` varchar(50) DEFAULT NULL,
  `USUARIO_MODIFICACION` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID_PRESCRIPCION`),
  KEY `ID_MEDICAMENTO` (`ID_MEDICAMENTO`),
  KEY `idx_prescripcion_consulta` (`ID_CONSULTA`),
  CONSTRAINT `tbl_prescripcion_ibfk_1` FOREIGN KEY (`ID_CONSULTA`) REFERENCES `tbl_consulta_medica` (`ID_CONSULTA`) ON DELETE CASCADE,
  CONSTRAINT `tbl_prescripcion_ibfk_2` FOREIGN KEY (`ID_MEDICAMENTO`) REFERENCES `tbl_inventario_medicamentos` (`ID_MEDICAMENTO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- 4. PROCEDIMIENTOS ALMACENADOS
-- ============================================================

DELIMITER $$

CREATE PROCEDURE `SP_REGISTRAR_BITACORA`(
    IN p_ID_USUARIO INT,
    IN p_ACCION VARCHAR(100),
    IN p_DESCRIPCION TEXT,
    IN p_MODULO VARCHAR(50),
    IN p_ID_REGISTRO_AFECTADO INT,
    IN p_TABLA_AFECTADA VARCHAR(50),
    IN p_IP_CLIENTE VARCHAR(45),
    IN p_USER_AGENT VARCHAR(500),
    IN p_ESTADO_OPERACION VARCHAR(20),
    IN p_DETALLE_ERROR TEXT,
    IN p_USUARIO_CREACION VARCHAR(50)
)
BEGIN
    DECLARE v_usuario_valido INT DEFAULT NULL;
    
    IF p_ID_USUARIO IS NOT NULL THEN
        SELECT ID_USUARIO INTO v_usuario_valido 
        FROM TBL_MS_USUARIO 
        WHERE ID_USUARIO = p_ID_USUARIO;
    END IF;
    
    IF v_usuario_valido IS NULL THEN
        SET p_ID_USUARIO = NULL;
    END IF;
    
    INSERT INTO TBL_MS_BITACORA (
        ID_USUARIO, ACCION, DESCRIPCION, MODULO, 
        ID_REGISTRO_AFECTADO, TABLA_AFECTADA, IP_CLIENTE, USER_AGENT,
        ESTADO_OPERACION, DETALLE_ERROR, USUARIO_CREACION
    ) VALUES (
        p_ID_USUARIO, p_ACCION, p_DESCRIPCION, p_MODULO,
        p_ID_REGISTRO_AFECTADO, p_TABLA_AFECTADA, p_IP_CLIENTE, p_USER_AGENT,
        p_ESTADO_OPERACION, p_DETALLE_ERROR, p_USUARIO_CREACION
    );
END$$

CREATE PROCEDURE `SP_ACTIVAR_2FA`(
    IN p_ID_USUARIO INT,
    IN p_SECRET_2FA VARCHAR(255),
    IN p_USUARIO_ACTUALIZACION VARCHAR(50)
)
BEGIN
    UPDATE TBL_MS_USUARIO 
    SET SECRET_2FA = p_SECRET_2FA,
        ACTIVO_2FA = 1,
        FECHA_ACTIVACION_2FA = CURRENT_TIMESTAMP,
        FECHA_MODIFICACION = CURRENT_TIMESTAMP,
        USUARIO_MODIFICACION = p_USUARIO_ACTUALIZACION
    WHERE ID_USUARIO = p_ID_USUARIO;
    
    CALL SP_REGISTRAR_BITACORA(
        p_ID_USUARIO,
        'ACTIVACION_2FA',
        'Usuario activó autenticación de dos factores',
        'SEGURIDAD',
        p_ID_USUARIO,
        'TBL_MS_USUARIO',
        NULL, NULL, 'EXITO', NULL,
        p_USUARIO_ACTUALIZACION
    );
    
    SELECT 'EXITO' AS RESULTADO, '2FA ACTIVADO CORRECTAMENTE' AS MENSAJE;
END$$

CREATE PROCEDURE `SP_CONSULTAR_BITACORA`(
    IN p_FECHA_INICIO DATETIME,
    IN p_FECHA_FIN DATETIME,
    IN p_ID_USUARIO INT,
    IN p_MODULO VARCHAR(50),
    IN p_ACCION VARCHAR(100)
)
BEGIN
    SELECT 
        b.ID_BITACORA,
        b.FECHA_HORA,
        COALESCE(u.USUARIO, 'SISTEMA') AS USUARIO,
        COALESCE(u.NOMBRE_USUARIO, 'SISTEMA') AS NOMBRE_USUARIO,
        b.ACCION,
        b.DESCRIPCION,
        b.MODULO,
        b.TABLA_AFECTADA,
        b.ID_REGISTRO_AFECTADO,
        b.IP_CLIENTE,
        b.ESTADO_OPERACION,
        b.DETALLE_ERROR
    FROM TBL_MS_BITACORA b
    LEFT JOIN TBL_MS_USUARIO u ON b.ID_USUARIO = u.ID_USUARIO
    WHERE 
        (p_FECHA_INICIO IS NULL OR b.FECHA_HORA >= p_FECHA_INICIO) AND
        (p_FECHA_FIN IS NULL OR b.FECHA_HORA <= p_FECHA_FIN) AND
        (p_ID_USUARIO IS NULL OR b.ID_USUARIO = p_ID_USUARIO) AND
        (p_MODULO IS NULL OR b.MODULO = p_MODULO) AND
        (p_ACCION IS NULL OR b.ACCION = p_ACCION)
    ORDER BY b.FECHA_HORA DESC;
END$$

CREATE PROCEDURE `SP_DESACTIVAR_2FA`(
    IN p_ID_USUARIO INT,
    IN p_USUARIO_ACTUALIZACION VARCHAR(50)
)
BEGIN
    UPDATE TBL_MS_USUARIO 
    SET ACTIVO_2FA = 0,
        SECRET_2FA = NULL,
        INTENTOS_2FA_FALLIDOS = 0,
        BLOQUEO_2FA_HASTA = NULL,
        FECHA_MODIFICACION = CURRENT_TIMESTAMP,
        USUARIO_MODIFICACION = p_USUARIO_ACTUALIZACION
    WHERE ID_USUARIO = p_ID_USUARIO;
    
    CALL SP_REGISTRAR_BITACORA(
        p_ID_USUARIO,
        'DESACTIVACION_2FA',
        'Usuario desactivó autenticación de dos factores',
        'SEGURIDAD',
        p_ID_USUARIO,
        'TBL_MS_USUARIO',
        NULL, NULL, 'EXITO', NULL,
        p_USUARIO_ACTUALIZACION
    );
    
    SELECT 'EXITO' AS RESULTADO, '2FA DESACTIVADO CORRECTAMENTE' AS MENSAJE;
END$$

CREATE PROCEDURE `SP_VALIDAR_CODIGO_2FA`(
    IN p_ID_USUARIO INT,
    IN p_CODIGO_2FA VARCHAR(10)
)
BEGIN
    DECLARE v_MAX_INTENTOS_2FA INT;
    DECLARE v_TIEMPO_BLOQUEO_MIN INT;
    DECLARE v_INTENTOS_2FA_FALLIDOS INT;
    DECLARE v_SECRET_2FA VARCHAR(255);
    DECLARE v_ACTIVO_2FA TINYINT(1);
    
    SELECT VALOR INTO v_MAX_INTENTOS_2FA FROM TBL_MS_PARAMETROS WHERE PARAMETRO = '2FA_MAX_INTENTOS';
    IF v_MAX_INTENTOS_2FA IS NULL THEN SET v_MAX_INTENTOS_2FA = 3; END IF;
    
    SELECT VALOR INTO v_TIEMPO_BLOQUEO_MIN FROM TBL_MS_PARAMETROS WHERE PARAMETRO = '2FA_TIEMPO_BLOQUEO_MIN';
    IF v_TIEMPO_BLOQUEO_MIN IS NULL THEN SET v_TIEMPO_BLOQUEO_MIN = 30; END IF;
    
    SELECT INTENTOS_2FA_FALLIDOS, SECRET_2FA, ACTIVO_2FA
    INTO v_INTENTOS_2FA_FALLIDOS, v_SECRET_2FA, v_ACTIVO_2FA
    FROM TBL_MS_USUARIO 
    WHERE ID_USUARIO = p_ID_USUARIO;
    
    IF v_ACTIVO_2FA != 1 THEN
        SELECT 'ERROR' AS RESULTADO, '2FA NO ESTÁ ACTIVADO PARA ESTE USUARIO' AS MENSAJE;
    ELSEIF v_INTENTOS_2FA_FALLIDOS >= v_MAX_INTENTOS_2FA THEN
        UPDATE TBL_MS_USUARIO 
        SET BLOQUEO_2FA_HASTA = DATE_ADD(NOW(), INTERVAL v_TIEMPO_BLOQUEO_MIN MINUTE),
            FECHA_MODIFICACION = CURRENT_TIMESTAMP,
            USUARIO_MODIFICACION = 'SISTEMA'
        WHERE ID_USUARIO = p_ID_USUARIO;
        
        SELECT 'ERROR' AS RESULTADO, 
               CONCAT('CUENTA BLOQUEADA POR EXCESO DE INTENTOS 2FA. ESPERE ', v_TIEMPO_BLOQUEO_MIN, ' MINUTOS.') AS MENSAJE;
    ELSE
        IF LENGTH(p_CODIGO_2FA) = 6 AND p_CODIGO_2FA REGEXP '^[0-9]+$' THEN
            UPDATE TBL_MS_USUARIO 
            SET INTENTOS_2FA_FALLIDOS = 0,
                BLOQUEO_2FA_HASTA = NULL,
                ULTIMO_CODIGO_2FA = p_CODIGO_2FA,
                FECHA_MODIFICACION = CURRENT_TIMESTAMP,
                USUARIO_MODIFICACION = 'SISTEMA'
            WHERE ID_USUARIO = p_ID_USUARIO;
            
            CALL SP_REGISTRAR_BITACORA(
                p_ID_USUARIO,
                'VALIDACION_2FA_EXITOSA',
                'Validación de código 2FA exitosa',
                'AUTENTICACION',
                p_ID_USUARIO,
                'TBL_MS_USUARIO',
                NULL, NULL, 'EXITO', NULL,
                'SISTEMA'
            );
            
            SELECT 'EXITO' AS RESULTADO, 'CÓDIGO 2FA VÁLIDO' AS MENSAJE;
        ELSE
            UPDATE TBL_MS_USUARIO 
            SET INTENTOS_2FA_FALLIDOS = v_INTENTOS_2FA_FALLIDOS + 1,
                FECHA_MODIFICACION = CURRENT_TIMESTAMP,
                USUARIO_MODIFICACION = 'SISTEMA'
            WHERE ID_USUARIO = p_ID_USUARIO;
            
            CALL SP_REGISTRAR_BITACORA(
                p_ID_USUARIO,
                'VALIDACION_2FA_FALLIDA',
                'Intento fallido de validación de código 2FA',
                'AUTENTICACION',
                p_ID_USUARIO,
                'TBL_MS_USUARIO',
                NULL, NULL, 'ERROR', 'Código 2FA inválido',
                'SISTEMA'
            );
            
            SELECT 'ERROR' AS RESULTADO, 'CÓDIGO 2FA INVÁLIDO' AS MENSAJE;
        END IF;
    END IF;
END$$

CREATE PROCEDURE `SP_VALIDAR_LOGIN`(
    IN p_USUARIO VARCHAR(50),
    IN p_CONTRASENA VARCHAR(255)
)
BEGIN
    DECLARE v_ID_USUARIO INT;
    DECLARE v_ESTADO VARCHAR(20);
    DECLARE v_INTENTOS_FALLIDOS INT;
    DECLARE v_MAX_INTENTOS INT;
    DECLARE v_CONTRASENA_DB VARCHAR(255);
    DECLARE v_FECHA_VENCIMIENTO DATE;
    DECLARE v_ES_PRIMER_INGRESO BOOLEAN;
    DECLARE v_ACTIVO_2FA TINYINT(1);
    DECLARE v_BLOQUEO_2FA_HASTA DATETIME;
    
    SELECT VALOR INTO v_MAX_INTENTOS FROM TBL_MS_PARAMETROS WHERE PARAMETRO = 'ADMIN_INTENTOS_INVALIDOS';
    IF v_MAX_INTENTOS IS NULL THEN SET v_MAX_INTENTOS = 3; END IF;
    
    SELECT ID_USUARIO, ESTADO, INTENTOS_FALLIDOS, CONTRASENA, FECHA_VENCIMIENTO, ACTIVO_2FA, BLOQUEO_2FA_HASTA
    INTO v_ID_USUARIO, v_ESTADO, v_INTENTOS_FALLIDOS, v_CONTRASENA_DB, v_FECHA_VENCIMIENTO, v_ACTIVO_2FA, v_BLOQUEO_2FA_HASTA
    FROM TBL_MS_USUARIO 
    WHERE USUARIO = UPPER(p_USUARIO);
    
    IF v_ID_USUARIO IS NULL THEN
        SELECT 'ERROR' AS RESULTADO, 'USUARIO/CONTRASEÑA INVÁLIDOS' AS MENSAJE, NULL AS ID_USUARIO, FALSE AS REQUIERE_2FA;
    ELSE
        IF v_BLOQUEO_2FA_HASTA IS NOT NULL AND v_BLOQUEO_2FA_HASTA > NOW() THEN
            SELECT 'ERROR' AS RESULTADO, 
                   CONCAT('CUENTA BLOQUEADA POR INTENTOS FALLIDOS DE 2FA HASTA: ', 
                          DATE_FORMAT(v_BLOQUEO_2FA_HASTA, '%Y-%m-%d %H:%i:%s')) AS MENSAJE, 
                   NULL AS ID_USUARIO, FALSE AS REQUIERE_2FA;
        ELSE
            IF v_ESTADO = 'BLOQUEADO' THEN
                SELECT 'ERROR' AS RESULTADO, 'USUARIO BLOQUEADO. CONTACTE AL ADMINISTRADOR.' AS MENSAJE, NULL AS ID_USUARIO, FALSE AS REQUIERE_2FA;
            ELSEIF v_ESTADO = 'INACTIVO' THEN
                SELECT 'ERROR' AS RESULTADO, 'USUARIO INACTIVO. CONTACTE AL ADMINISTRADOR.' AS MENSAJE, NULL AS ID_USUARIO, FALSE AS REQUIERE_2FA;
            ELSEIF v_INTENTOS_FALLIDOS >= v_MAX_INTENTOS THEN
                UPDATE TBL_MS_USUARIO SET ESTADO = 'BLOQUEADO' WHERE ID_USUARIO = v_ID_USUARIO;
                SELECT 'ERROR' AS RESULTADO, 'USUARIO BLOQUEADO POR EXCESO DE INTENTOS FALLIDOS.' AS MENSAJE, NULL AS ID_USUARIO, FALSE AS REQUIERE_2FA;
            ELSEIF v_CONTRASENA_DB != p_CONTRASENA THEN
                UPDATE TBL_MS_USUARIO 
                SET INTENTOS_FALLIDOS = INTENTOS_FALLIDOS + 1,
                    FECHA_MODIFICACION = CURRENT_TIMESTAMP,
                    USUARIO_MODIFICACION = 'SISTEMA'
                WHERE ID_USUARIO = v_ID_USUARIO;
                
                SELECT 'ERROR' AS RESULTADO, 'USUARIO/CONTRASEÑA INVÁLIDOS' AS MENSAJE, NULL AS ID_USUARIO, FALSE AS REQUIERE_2FA;
            ELSE
                UPDATE TBL_MS_USUARIO 
                SET INTENTOS_FALLIDOS = 0,
                    INTENTOS_2FA_FALLIDOS = 0,
                    BLOQUEO_2FA_HASTA = NULL,
                    FECHA_ULTIMA_CONEXION = CURRENT_TIMESTAMP,
                    FECHA_MODIFICACION = CURRENT_TIMESTAMP,
                    USUARIO_MODIFICACION = 'SISTEMA'
                WHERE ID_USUARIO = v_ID_USUARIO;
                
                SET v_ES_PRIMER_INGRESO = (v_ESTADO = 'NUEVO');
                
                IF v_ACTIVO_2FA = 1 THEN
                    SELECT 'REQUIERE_2FA' AS RESULTADO, 'SE REQUIERE CÓDIGO DE AUTENTICACIÓN DE DOS FACTORES' AS MENSAJE, 
                           v_ID_USUARIO AS ID_USUARIO, TRUE AS REQUIERE_2FA;
                ELSE
                    SELECT 'EXITO' AS RESULTADO, 'LOGIN EXITOSO' AS MENSAJE, v_ID_USUARIO AS ID_USUARIO, 
                           FALSE AS REQUIERE_2FA, v_ES_PRIMER_INGRESO AS PRIMER_INGRESO;
                END IF;
            END IF;
        END IF;
    END IF;
END$$

DELIMITER ;

-- ============================================================
-- 5. TRIGGERS DE AUDITORÍA
-- ============================================================

DELIMITER $$

CREATE TRIGGER `TR_AUDITORIA_CITAS_INSERT` AFTER INSERT ON `tbl_citas` FOR EACH ROW
BEGIN
    CALL SP_REGISTRAR_BITACORA(
        COALESCE(NEW.ID_USUARIOCREADOR, 1),
        'CREACION_CITA',
        CONCAT('Cita creada para paciente ID: ', NEW.ID_PACIENTE, ' con doctor ID: ', NEW.ID_DOCTOR, ' - ', NEW.ESTADO),
        'CITAS',
        NEW.ID_CITA,
        'TBL_CITAS',
        NULL, NULL, 'EXITO', NULL,
        'TRIGGER'
    );
END$$

CREATE TRIGGER `TR_AUDITORIA_CITAS_UPDATE` AFTER UPDATE ON `tbl_citas` FOR EACH ROW
BEGIN
    IF OLD.ESTADO != NEW.ESTADO THEN
        CALL SP_REGISTRAR_BITACORA(
            COALESCE((SELECT ID_USUARIO FROM TBL_MS_USUARIO WHERE USUARIO = COALESCE(NEW.USUARIO_MODIFICACION, 'SISTEMA')), 1),
            'CAMBIO_ESTADO_CITA',
            CONCAT('Cita ID ', NEW.ID_CITA, ' cambió de ', OLD.ESTADO, ' a ', NEW.ESTADO),
            'CITAS',
            NEW.ID_CITA,
            'TBL_CITAS',
            NULL, NULL, 'EXITO', NULL,
            'TRIGGER'
        );
    END IF;
END$$

CREATE TRIGGER `TR_AUDITORIA_CONSULTAS_INSERT` AFTER INSERT ON `tbl_consulta_medica` FOR EACH ROW
BEGIN
    CALL SP_REGISTRAR_BITACORA(
        COALESCE(NEW.ID_DOCTOR, 1),
        'REGISTRO_CONSULTA',
        CONCAT('Consulta médica registrada para paciente ID: ', NEW.ID_PACIENTE, ' - Diagnóstico: ', COALESCE(LEFT(NEW.DIAGNOSTICO_PRINCIPAL, 50), 'SIN DIAGNÓSTICO')),
        'CONSULTAS',
        NEW.ID_CONSULTA,
        'TBL_CONSULTA_MEDICA',
        NULL, NULL, 'EXITO', NULL,
        'TRIGGER'
    );
END$$

CREATE TRIGGER `TR_AUDITORIA_MEDICAMENTOS_INSERT` AFTER INSERT ON `tbl_inventario_medicamentos` FOR EACH ROW
BEGIN
    CALL SP_REGISTRAR_BITACORA(
        COALESCE(NEW.ID_USUARIO_REGISTRO, 1),
        'CREACION_MEDICAMENTO',
        CONCAT('Medicamento agregado: ', NEW.NOMBRE_MEDICAMENTO, ' - Stock: ', NEW.STOCK_ACTUAL),
        'FARMACIA',
        NEW.ID_MEDICAMENTO,
        'TBL_INVENTARIO_MEDICAMENTO',
        NULL, NULL, 'EXITO', NULL,
        'TRIGGER'
    );
END$$

CREATE TRIGGER `TR_AUDITORIA_MEDICAMENTOS_UPDATE` AFTER UPDATE ON `tbl_inventario_medicamentos` FOR EACH ROW
BEGIN
    DECLARE v_cambios TEXT DEFAULT '';
    DECLARE v_id_usuario_modificador INT;
    
    IF OLD.STOCK_ACTUAL != NEW.STOCK_ACTUAL THEN
        SET v_cambios = CONCAT(v_cambios, 'Stock: ', OLD.STOCK_ACTUAL, ' → ', NEW.STOCK_ACTUAL, '; ');
    END IF;
    
    IF OLD.PRECIO_VENTA != NEW.PRECIO_VENTA THEN
        SET v_cambios = CONCAT(v_cambios, 'Precio: ', OLD.PRECIO_VENTA, ' → ', NEW.PRECIO_VENTA, '; ');
    END IF;
    
    IF OLD.ESTADO != NEW.ESTADO THEN
        SET v_cambios = CONCAT(v_cambios, 'Estado: ', OLD.ESTADO, ' → ', NEW.ESTADO, '; ');
    END IF;
    
    IF v_cambios != '' THEN
        SELECT COALESCE(ID_USUARIO, 1) INTO v_id_usuario_modificador 
        FROM TBL_MS_USUARIO 
        WHERE USUARIO = COALESCE(NEW.USUARIO_MODIFICACION, 'SISTEMA')
        LIMIT 1;
        
        CALL SP_REGISTRAR_BITACORA(
            v_id_usuario_modificador,
            'ACTUALIZACION_MEDICAMENTO',
            CONCAT('Medicamento actualizado: ', NEW.NOMBRE_MEDICAMENTO, ' - Cambios: ', v_cambios),
            'FARMACIA',
            NEW.ID_MEDICAMENTO,
            'TBL_INVENTARIO_MEDICAMENTO',
            NULL, NULL, 'EXITO', NULL,
            'TRIGGER'
        );
    END IF;
END$$

CREATE TRIGGER `TR_AUDITORIA_PARAMETROS_UPDATE` AFTER UPDATE ON `tbl_ms_parametros` FOR EACH ROW
BEGIN
    DECLARE v_id_usuario_modificador INT;
    
    IF OLD.VALOR != NEW.VALOR THEN
        SELECT COALESCE(ID_USUARIO, 1) INTO v_id_usuario_modificador 
        FROM TBL_MS_USUARIO 
        WHERE USUARIO = COALESCE(NEW.USUARIO_MODIFICACION, 'SISTEMA')
        LIMIT 1;
        
        CALL SP_REGISTRAR_BITACORA(
            v_id_usuario_modificador,
            'ACTUALIZACION_PARAMETRO',
            CONCAT('Parámetro actualizado: ', NEW.PARAMETRO, ' - Valor: ', OLD.VALOR, ' → ', NEW.VALOR),
            'CONFIGURACION',
            NEW.ID_PARAMETRO,
            'TBL_MS_PARAMETROS',
            NULL, NULL, 'EXITO', NULL,
            'TRIGGER'
        );
    END IF;
END$$

CREATE TRIGGER `TR_AUDITORIA_ROLES_INSERT` AFTER INSERT ON `tbl_ms_roles` FOR EACH ROW
BEGIN
    DECLARE v_id_usuario_creador INT;
    
    SELECT COALESCE(ID_USUARIO, 1) INTO v_id_usuario_creador 
    FROM TBL_MS_USUARIO 
    WHERE USUARIO = COALESCE(NEW.USUARIO_CREACION, 'SISTEMA')
    LIMIT 1;
    
    CALL SP_REGISTRAR_BITACORA(
        v_id_usuario_creador,
        'CREACION_ROL',
        CONCAT('Nuevo rol creado: ', NEW.ROL),
        'ROLES',
        NEW.ID_ROL,
        'TBL_MS_ROLES',
        NULL, NULL, 'EXITO', NULL,
        'TRIGGER'
    );
END$$

CREATE TRIGGER `TR_AUDITORIA_USUARIOS_INSERT` AFTER INSERT ON `tbl_ms_usuario` FOR EACH ROW
BEGIN
    DECLARE v_id_usuario_creador INT;
    
    SELECT COALESCE(ID_USUARIO, 1) INTO v_id_usuario_creador 
    FROM TBL_MS_USUARIO 
    WHERE USUARIO = COALESCE(NEW.USUARIO_CREACION, 'SISTEMA')
    LIMIT 1;
    
    CALL SP_REGISTRAR_BITACORA(
        v_id_usuario_creador,
        'CREACION_USUARIO',
        CONCAT('Nuevo usuario creado: ', NEW.USUARIO, ' - ', NEW.NOMBRE_USUARIO),
        'USUARIOS',
        NEW.ID_USUARIO,
        'TBL_MS_USUARIO',
        NULL, NULL, 'EXITO', NULL,
        'TRIGGER'
    );
END$$

CREATE TRIGGER `TR_AUDITORIA_2FA_UPDATE` AFTER UPDATE ON `tbl_ms_usuario` FOR EACH ROW
BEGIN
    IF OLD.ACTIVO_2FA != NEW.ACTIVO_2FA THEN
        IF NEW.ACTIVO_2FA = 1 THEN
            CALL SP_REGISTRAR_BITACORA(
                NEW.ID_USUARIO,
                'ACTIVACION_2FA',
                'Usuario activó autenticación de dos factores',
                'SEGURIDAD',
                NEW.ID_USUARIO,
                'TBL_MS_USUARIO',
                NULL, NULL, 'EXITO', NULL,
                'TRIGGER'
            );
        ELSE
            CALL SP_REGISTRAR_BITACORA(
                NEW.ID_USUARIO,
                'DESACTIVACION_2FA',
                'Usuario desactivó autenticación de dos factores',
                'SEGURIDAD',
                NEW.ID_USUARIO,
                'TBL_MS_USUARIO',
                NULL, NULL, 'EXITO', NULL,
                'TRIGGER'
            );
        END IF;
    END IF;
END$$

CREATE TRIGGER `TR_AUDITORIA_USUARIOS_UPDATE` AFTER UPDATE ON `tbl_ms_usuario` FOR EACH ROW
BEGIN
    DECLARE v_cambios TEXT DEFAULT '';
    DECLARE v_id_usuario_modificador INT;
    
    SELECT COALESCE(ID_USUARIO, 1) INTO v_id_usuario_modificador 
    FROM TBL_MS_USUARIO 
    WHERE USUARIO = COALESCE(NEW.USUARIO_MODIFICACION, 'SISTEMA')
    LIMIT 1;
    
    IF OLD.ESTADO != NEW.ESTADO THEN
        SET v_cambios = CONCAT(v_cambios, 'Estado: ', OLD.ESTADO, ' → ', NEW.ESTADO, '; ');
    END IF;
    
    IF OLD.INTENTOS_FALLIDOS != NEW.INTENTOS_FALLIDOS THEN
        SET v_cambios = CONCAT(v_cambios, 'Intentos: ', OLD.INTENTOS_FALLIDOS, ' → ', NEW.INTENTOS_FALLIDOS, '; ');
    END IF;
    
    IF OLD.ACTIVO_2FA != NEW.ACTIVO_2FA THEN
        SET v_cambios = CONCAT(v_cambios, '2FA: ', OLD.ACTIVO_2FA, ' → ', NEW.ACTIVO_2FA, '; ');
    END IF;
    
    IF v_cambios = '' THEN
        SET v_cambios = 'Actualización general del usuario';
    END IF;
    
    CALL SP_REGISTRAR_BITACORA(
        v_id_usuario_modificador,
        'ACTUALIZACION_USUARIO',
        CONCAT('Usuario actualizado: ', NEW.USUARIO, ' - Cambios: ', v_cambios),
        'USUARIOS',
        NEW.ID_USUARIO,
        'TBL_MS_USUARIO',
        NULL, NULL, 'EXITO', NULL,
        'TRIGGER'
    );
END$$

CREATE TRIGGER `TR_AUDITORIA_PACIENTES_INSERT` AFTER INSERT ON `tbl_paciente` FOR EACH ROW
BEGIN
    CALL SP_REGISTRAR_BITACORA(
        COALESCE(NEW.ID_USUARIO_REGISTRO, 1),
        'CREACION_PACIENTE',
        CONCAT('Nuevo paciente creado: ', NEW.NOMBRES, ' ', NEW.APELLIDOS, ' (', NEW.NUMERO_DOCUMENTO_IDENTIDAD, ')'),
        'PACIENTES',
        NEW.ID_PACIENTE,
        'TBL_PACIENTE',
        NULL, NULL, 'EXITO', NULL,
        'TRIGGER'
    );
END$$

CREATE TRIGGER `TR_AUDITORIA_PACIENTES_UPDATE` AFTER UPDATE ON `tbl_paciente` FOR EACH ROW
BEGIN
    CALL SP_REGISTRAR_BITACORA(
        COALESCE(NEW.ID_USUARIO_REGISTRO, 1),
        'ACTUALIZACION_PACIENTE',
        CONCAT('Paciente actualizado: ', NEW.NOMBRES, ' ', NEW.APELLIDOS),
        'PACIENTES',
        NEW.ID_PACIENTE,
        'TBL_PACIENTE',
        NULL, NULL, 'EXITO', NULL,
        'TRIGGER'
    );
END$$

CREATE TRIGGER `TR_AUDITORIA_PRESCRIPCIONES_INSERT` AFTER INSERT ON `tbl_prescripcion` FOR EACH ROW
BEGIN
    DECLARE v_medicamento_nombre VARCHAR(255);
    DECLARE v_id_doctor INT;
    
    SELECT COALESCE(NOMBRE_MEDICAMENTO, 'MEDICAMENTO DESCONOCIDO') INTO v_medicamento_nombre 
    FROM TBL_INVENTARIO_MEDICAMENTO 
    WHERE ID_MEDICAMENTO = NEW.ID_MEDICAMENTO;
    
    SELECT COALESCE(ID_DOCTOR, 1) INTO v_id_doctor 
    FROM TBL_CONSULTA_MEDICA 
    WHERE ID_CONSULTA = NEW.ID_CONSULTA;
    
    CALL SP_REGISTRAR_BITACORA(
        v_id_doctor,
        'PRESCRIPCION_MEDICA',
        CONCAT('Prescripción de ', v_medicamento_nombre, ' - Dosis: ', NEW.DOSIS),
        'FARMACIA',
        NEW.ID_PRESCRIPCION,
        'TBL_PRESCRIPCION',
        NULL, NULL, 'EXITO', NULL,
        'TRIGGER'
    );
END$$

DELIMITER ;

-- ============================================================
-- 6. VISTAS FINALES
-- ============================================================

DROP VIEW IF EXISTS `vw_bitacora_completa`;
CREATE ALGORITHM=UNDEFINED
VIEW `vw_bitacora_completa` AS SELECT 
    b.`ID_BITACORA`,
    b.`FECHA_HORA`,
    COALESCE(u.`USUARIO`, 'SISTEMA') AS `USUARIO`,
    COALESCE(u.`NOMBRE_USUARIO`, 'SISTEMA') AS `NOMBRE_USUARIO`,
    COALESCE(r.`ROL`, 'SISTEMA') AS `ROL`,
    b.`ACCION`,
    b.`DESCRIPCION`,
    b.`MODULO`,
    b.`TABLA_AFECTADA`,
    b.`ID_REGISTRO_AFECTADO`,
    b.`IP_CLIENTE`,
    b.`ESTADO_OPERACION`,
    b.`DETALLE_ERROR`,
    b.`USER_AGENT`
FROM `tbl_ms_bitacora` b
LEFT JOIN `tbl_ms_usuario` u ON b.`ID_USUARIO` = u.`ID_USUARIO`
LEFT JOIN `tbl_ms_roles` r ON u.`ID_ROL` = r.`ID_ROL`;

DROP VIEW IF EXISTS `vw_citas_completas`;
CREATE ALGORITHM=UNDEFINED
VIEW `vw_citas_completas` AS SELECT 
    c.`ID_CITA`,
    c.`FECHA_CITA`,
    c.`FECHA_FIN_ESTIMADA`,
    c.`ESTADO` AS `ESTADO_CITA`,
    c.`PRIORIDAD`,
    c.`TIPO_CITA`,
    p.`ID_PACIENTE`,
    CONCAT(p.`NOMBRES`, ' ', p.`APELLIDOS`) AS `NOMBRE_PACIENTE`,
    p.`TELEFONO`,
    p.`CORREO_ELECTRONICO`,
    u.`ID_USUARIO` AS `ID_DOCTOR`,
    u.`NOMBRE_USUARIO` AS `NOMBRE_DOCTOR`,
    COALESCE(e.`NOMBRE_ESPECIALIDAD`, 'SIN ESPECIALIDAD') AS `NOMBRE_ESPECIALIDAD`,
    c.`MOTIVO_CONSULTA`,
    c.`OBSERVACIONES`
FROM `tbl_citas` c
JOIN `tbl_paciente` p ON c.`ID_PACIENTE` = p.`ID_PACIENTE`
JOIN `tbl_ms_usuario` u ON c.`ID_DOCTOR` = u.`ID_USUARIO`
LEFT JOIN `tbl_doctor_especialidad` de ON u.`ID_USUARIO` = de.`ID_DOCTOR` AND de.`ES_PRIMARIA` = 1
LEFT JOIN `tbl_especialidades` e ON de.`ID_ESPECIALIDAD` = e.`ID_ESPECIALIDAD`;

DROP VIEW IF EXISTS `vw_estadisticas_bitacora`;
CREATE ALGORITHM=UNDEFINED
VIEW `vw_estadisticas_bitacora` AS SELECT 
    CAST(`FECHA_HORA` AS DATE) AS `FECHA`,
    `MODULO`,
    `ESTADO_OPERACION`,
    COUNT(*) AS `TOTAL_OPERACIONES`,
    COUNT(DISTINCT `ID_USUARIO`) AS `USUARIOS_ACTIVOS`
FROM `tbl_ms_bitacora`
GROUP BY CAST(`FECHA_HORA` AS DATE), `MODULO`, `ESTADO_OPERACION`;

DROP VIEW IF EXISTS `vw_estado_seguridad_2fa`;
CREATE ALGORITHM=UNDEFINED
VIEW `vw_estado_seguridad_2fa` AS SELECT 
    u.`ID_USUARIO`,
    u.`USUARIO`,
    u.`NOMBRE_USUARIO`,
    u.`ACTIVO_2FA`,
    u.`FECHA_ACTIVACION_2FA`,
    u.`INTENTOS_2FA_FALLIDOS`,
    u.`BLOQUEO_2FA_HASTA`,
    r.`ROL`,
    CASE 
        WHEN u.`ACTIVO_2FA` = 1 THEN 'PROTEGIDO'
        ELSE 'VULNERABLE'
    END AS `ESTADO_SEGURIDAD`
FROM `tbl_ms_usuario` u
JOIN `tbl_ms_roles` r ON u.`ID_ROL` = r.`ID_ROL`;

DROP VIEW IF EXISTS `vw_usuarios_completos`;
CREATE ALGORITHM=UNDEFINED
VIEW `vw_usuarios_completos` AS SELECT 
    u.`ID_USUARIO`,
    u.`USUARIO`,
    u.`NOMBRE_USUARIO`,
    u.`ESTADO`,
    u.`CORREO_ELECTRONICO`,
    u.`FECHA_ULTIMA_CONEXION`,
    u.`FECHA_VENCIMIENTO`,
    u.`INTENTOS_FALLIDOS`,
    u.`ACTIVO_2FA`,
    u.`FECHA_ACTIVACION_2FA`,
    u.`INTENTOS_2FA_FALLIDOS`,
    u.`BLOQUEO_2FA_HASTA`,
    r.`ROL`,
    r.`DESCRIPCION` AS `DESCRIPCION_ROL`
FROM `tbl_ms_usuario` u
JOIN `tbl_ms_roles` r ON u.`ID_ROL` = r.`ID_ROL`;

-- ============================================================
-- 7. ACTUALIZACIONES POST-CREACIÓN
-- ============================================================

-- Asegurar que ADMIN tiene el rol correcto
UPDATE tbl_ms_usuario
SET ID_ROL = 1
WHERE UPPER(USUARIO) = 'ADMIN';

ALTER TABLE tbl_paciente AUTO_INCREMENT = 1;

-- ============================================================
-- 8. RESTAURACIÓN DE CONFIGURACIÓN
-- ============================================================

SET TIME_ZONE=@OLD_TIME_ZONE;
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT;
SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS;
SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION;
SET SQL_NOTES=@OLD_SQL_NOTES;
SET SQL_SAFE_UPDATES = 1;

-- ============================================================
-- 9. VERIFICACIÓN FINAL
-- ============================================================

SELECT '========================================' AS '';
SELECT 'BASE DE DATOS ROCA_MAYA INSTALADA CORRECTAMENTE' AS 'MENSAJE';
SELECT '========================================' AS '';
SELECT CONCAT('Tablas creadas: ', COUNT(*)) AS 'RESULTADO' FROM information_schema.tables WHERE table_schema = 'roca_maya';
SELECT CONCAT('Vistas creadas: ', COUNT(*)) AS 'RESULTADO' FROM information_schema.views WHERE table_schema = 'roca_maya';
SELECT CONCAT('Procedimientos: ', COUNT(*)) AS 'RESULTADO' FROM information_schema.routines WHERE routine_schema = 'roca_maya' AND routine_type = 'PROCEDURE';
SELECT CONCAT('Triggers: ', COUNT(*)) AS 'RESULTADO' FROM information_schema.triggers WHERE trigger_schema = 'roca_maya';
SELECT '========================================' AS '';

SELECT ID_USUARIO, USUARIO, NOMBRE_USUARIO, ROL 
FROM tbl_ms_usuario u 
JOIN tbl_ms_roles r ON u.ID_ROL = r.ID_ROL;